Repository apache/opennlp, pull requests merged in 2025-07, with the labels that each got.

#810 OPENNLP-1753: Switch to pre-trained Model binaries v1.3 (OpenNLP 2.x)
  opennlp-docs/src/docbkx/lemmatizer.xml
  opennlp-docs/src/docbkx/postagger.xml
  opennlp-docs/src/docbkx/sentdetect.xml
  opennlp-docs/src/docbkx/tokenizer.xml
  opennlp-tools/src/main/java/opennlp/tools/monitoring/StopCriteria.java
  opennlp-tools/src/main/java/opennlp/tools/util/DownloadUtil.java
  opennlp-tools/src/test/java/opennlp/tools/AbstractModelLoaderTest.java
  opennlp-tools/src/test/java/opennlp/tools/cmdline/lemmatizer/LemmatizerModelLoaderIT.java
  opennlp-tools/src/test/java/opennlp/tools/cmdline/postag/POSModelLoaderIT.java
  opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderIT.java
  opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderIT.java
  opennlp-tools/src/test/java/opennlp/tools/formats/TwentyNewsgroupSampleStreamFactoryTest.java
  opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratNameSampleStreamFactoryTest.java
  opennlp-tools/src/test/java/opennlp/tools/formats/muc/Muc6NameSampleStreamFactoryTest.java
  opennlp-tools/src/test/java/opennlp/tools/monitoring/DefaultTrainingProgressMonitorTest.java
  opennlp-tools/src/test/java/opennlp/tools/util/DownloadParserTest.java
  opennlp-tools/src/test/resources/opennlp/tools/util/index.html
  opennlp-uima/src/test/java/opennlp/uima/util/OpennlpUtilTest.java
  opennlp-uima/src/test/resources/test-descriptors/OpenNlpTextAnalyzer.xml
  opennlp-uima/src/test/resources/test-descriptors/PosTagger.xml
  opennlp-uima/src/test/resources/test-descriptors/SentenceDetector.xml
  opennlp-uima/src/test/resources/test-descriptors/Tokenizer.xml
  pom.xml
Labels: dependencies, java, tests

#813 OPENNLP-1758: Enhance Javadoc of UIMA extension
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/Chunker.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/ChunkerModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/ChunkerModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/dictionary/DictionaryResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/dictionary/DictionaryResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/doccat/DoccatModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/doccat/DoccatModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/NameFinder.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/TokenNameFinderModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/TokenNameFinderModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/Parser.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/ParserModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/ParserModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSTagger.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/AbstractSentenceDetector.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceDetector.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/AbstractTokenizer.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/SimpleTokenizer.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/Tokenizer.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/TokenizerModelResource.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/TokenizerModelResourceImpl.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/WhitespaceTokenizer.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/util/OpenNlpAnnotatorProcessException.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/util/UimaUtil.java
Labels: documentation

#817 OPENNLP-1760: Make SourceForge URLs in Tests configurable to avoid 403/Rate limiting issues
  opennlp-core/opennlp-cli/src/test/java/opennlp/tools/AbstractModelLoaderTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/AbstractModelLoaderTest.java
  opennlp-extensions/opennlp-uima/src/test/java/opennlp/uima/AbstractIT.java
  opennlp-tools/src/test/java/opennlp/tools/namefind/AbstractNameFinderTest.java
  pom.xml
Labels: tests, build

#812 OPENNLP-1757: Expose probs() method in thread-safe probabilistic ME classes
  opennlp-api/src/main/java/opennlp/tools/ml/Probabilistic.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/chunker/ChunkerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/chunker/ThreadSafeChunkerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/langdetect/ThreadSafeLanguageDetectorME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/lemmatizer/LemmatizerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/lemmatizer/ThreadSafeLemmatizerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/namefind/NameFinderME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/namefind/ThreadSafeNameFinderME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/postag/POSTaggerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/postag/ThreadSafePOSTaggerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/sentdetect/ThreadSafeSentenceDetectorME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/tokenize/ThreadSafeTokenizerME.java
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/tokenize/TokenizerME.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEDutchTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEFrenchTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEGermanTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEIT.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEItalianTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEPolishTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEPortugueseTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMESpanishTest.java
  opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMETest.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceDetector.java
  opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/Tokenizer.java
Labels: java

#814 OPENNLP-1759: Optimize computation of hashCode in StringList
  opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/util/StringList.java
  opennlp-extensions/opennlp-uima/src/test/java/opennlp/uima/dictionary/DictionaryResourceTest.java
Labels: java

#820 Update copyright year in several files
  LICENSE
  opennlp-distr/src/main/readme/NOTICE
  opennlp-docs/src/docbkx/opennlp.xml
Labels: dependencies, documentation

#822 OPENNLP-1762: Fix mvn clean install by setting default download property to SourceForge for surefire/failsafe (OpenNLP 2.x)
  pom.xml
Labels: build
